<?php
declare(strict_types=1);

require dirname(__DIR__) . '/config/database.php';

function sql_value($value): string {
    if ($value === null) {
        return 'NULL';
    }
    return "'" . str_replace("'", "''", (string) $value) . "'";
}

$db = get_db();

$captains = $db->query("
    SELECT id, captain_name, phone_number, created_at, created_by, visible
    FROM captains
    WHERE id NOT LIKE 'c-%'
    ORDER BY
        CASE WHEN id REGEXP '^[0-9]+$' THEN 0 ELSE 1 END,
        CAST(id AS UNSIGNED),
        id
")->fetchAll(PDO::FETCH_ASSOC);

if (!$captains) {
    echo "No non-c captain IDs found." . PHP_EOL;
    exit;
}

$maxC = (int) $db->query("
    SELECT COALESCE(MAX(CAST(SUBSTRING(id, 3) AS UNSIGNED)), 0)
    FROM captains
    WHERE id REGEXP '^c-[0-9]+$'
")->fetchColumn();

$insertCaptain = $db->prepare("
    INSERT INTO captains
        (id, captain_name, phone_number, created_at, created_by, visible)
    VALUES
        (:new_id, :captain_name, :phone_number, :created_at, :created_by, :visible)
");
$insertBranches = $db->prepare("
    INSERT IGNORE INTO captain_branch (branch_id, captain_id)
    SELECT branch_id, :new_id
    FROM captain_branch
    WHERE captain_id = :old_id
");
$updateReceipts = $db->prepare("
    UPDATE receipts
    SET captain_id = :new_id
    WHERE captain_id = :old_id
");
$deleteBranches = $db->prepare("DELETE FROM captain_branch WHERE captain_id = ?");
$deleteCaptain  = $db->prepare("DELETE FROM captains WHERE id = ?");

$mappings = [];
$sqlLines = [
    '-- Exact replay for converting non-c captain IDs to c-prefixed IDs.',
    '-- Generated by migrations/convert_non_c_captains_to_c_ids.php.',
    '',
    'START TRANSACTION;',
    '',
];

$db->beginTransaction();
try {
    foreach ($captains as $captain) {
        $oldId = (string) $captain['id'];
        $newId = 'c-' . (++$maxC);

        $insertCaptain->execute([
            ':new_id'       => $newId,
            ':captain_name' => $captain['captain_name'],
            ':phone_number' => $captain['phone_number'],
            ':created_at'   => $captain['created_at'],
            ':created_by'   => $captain['created_by'],
            ':visible'      => $captain['visible'],
        ]);

        $insertBranches->execute([
            ':new_id' => $newId,
            ':old_id' => $oldId,
        ]);

        $updateReceipts->execute([
            ':new_id' => $newId,
            ':old_id' => $oldId,
        ]);

        $deleteBranches->execute([$oldId]);
        $deleteCaptain->execute([$oldId]);

        $mappings[] = [$oldId, $newId, (string) $captain['captain_name']];

        $sqlLines[] = "INSERT INTO captains (id, captain_name, phone_number, created_at, created_by, visible) VALUES ("
            . sql_value($newId) . ', '
            . sql_value($captain['captain_name']) . ', '
            . sql_value($captain['phone_number']) . ', '
            . sql_value($captain['created_at']) . ', '
            . sql_value($captain['created_by']) . ', '
            . sql_value($captain['visible'])
            . ') ON DUPLICATE KEY UPDATE captain_name = VALUES(captain_name), phone_number = VALUES(phone_number), created_at = VALUES(created_at), created_by = VALUES(created_by), visible = VALUES(visible);';
        $sqlLines[] = "INSERT IGNORE INTO captain_branch (branch_id, captain_id) SELECT branch_id, " . sql_value($newId) . " FROM captain_branch WHERE captain_id = " . sql_value($oldId) . ';';
        $sqlLines[] = "UPDATE receipts SET captain_id = " . sql_value($newId) . " WHERE captain_id = " . sql_value($oldId) . ';';
        $sqlLines[] = "DELETE FROM captain_branch WHERE captain_id = " . sql_value($oldId) . ';';
        $sqlLines[] = "DELETE FROM captains WHERE id = " . sql_value($oldId) . ';';
        $sqlLines[] = '';
    }

    $db->commit();
} catch (Throwable $e) {
    $db->rollBack();
    throw $e;
}

$sqlLines[] = 'COMMIT;';
$sqlLines[] = '';
file_put_contents(__DIR__ . '/convert_non_c_captains_to_c_ids_applied.sql', implode(PHP_EOL, $sqlLines));

echo "Converted captain IDs: " . count($mappings) . PHP_EOL;
foreach ($mappings as [$oldId, $newId, $name]) {
    echo $oldId . " -> " . $newId . " (" . $name . ")" . PHP_EOL;
}
